#!/bin/bash

set -e

if [[ ! -z $DEBUG ]]; then
  set -x
fi

core=$1

if [[ -z "$core" ]]; then
    echo >&2 'Error. Core name have to be defined'
    exit 1
fi

echo "Creating core with a default configuration:"
solr create_core -c "$core"
echo 'Done!'
