#!/bin/sh

set -e

if [[ ! -z $DEBUG ]]; then
  set -x
fi

core=$1

if [[ -z "$core" ]]; then
    echo >&2 'Error. Core name have to be defined'
    exit 1
fi

curl -s "http://localhost:8983/solr/admin/cores?action=RELOAD&core=$core"
echo 'Done!'
