#!/bin/bash

set -e

if [[ ! -z $DEBUG ]]; then
  set -x
fi

core=$1
schema=$2

if [[ -z "$core" ]]; then
    echo >&2 'Error. Core name have to be defined'
    exit 1
fi

rm -rf /tmp/schema
mkdir -p /tmp/schema
cd /tmp/schema

if [[ "$schema" = 'drupal8' ]]; then
    wget -nv https://ftp.drupal.org/files/projects/search_api_solr-8.x-1.0-beta1.tar.gz
    tar xzf search_api_solr*
    solr create_core -c "$core" -d ./search_api_solr/solr-conf/5.x/
elif [[ "$schema" = 'drupal7' ]]; then
    wget -nv https://ftp.drupal.org/files/projects/search_api_solr-7.x-1.11.tar.gz
    tar xzf search_api_solr*
    solr create_core -c "$core" -d ./search_api_solr/solr-conf/5.x/
else
    echo "Warning. Unknown schema specified: '$schema'"
    solr create_core -c "$core"
fi

rm -rf /tmp/schema
echo 'Done!'
