name: Build
description: Build solr image
inputs:
  version:
    description: version
    required: true
  tags:
    description: image tags
    required: true
  alpine_ver:
    description: alpine version
    required: true
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      SOLR_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      ALPINE_VER: ${{ inputs.alpine_ver }}
    run: |
      set -e
      make
      make test
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
